max_width = 79
hard_tabs = false
tab_spaces = 2
newline_style = "Auto"
indent_style = "Block"
width_heuristics = "Max"
wrap_comments = true
format_code_in_doc_comments = false
comment_width = 79
normalize_comments = false
normalize_doc_attributes = false
license_template_path = ""
format_strings = false
format_macro_matchers = false
format_macro_bodies = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = true
where_single_line = false
imports_indent = "Block"
imports_layout = "HorizontalVertical"
merge_imports = false
group_imports = "StdExternalCrate"
reorder_imports = true
reorder_modules = true
reorder_impl_items = false
type_punctuation_density = "Wide"
space_before_colon = false
space_after_colon = true
space_around_attr_eq = true
spaces_around_ranges = false
binop_separator = "Back"
space_before_fn_sig_paren = false
remove_nested_parens = true
combine_control_expr = true
overflow_delimited_expr = false
struct_field_align_threshold = 0
enum_discrim_align_threshold = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
force_multiline_blocks = false
fn_params_layout = "Tall"
brace_style = "AlwaysNextLine"
control_brace_style = "AlwaysNextLine"
trailing_semicolon = true
trailing_comma = "Vertical"
match_block_trailing_comma = true
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
edition = "2018"
inline_attribute_width = 0
format_generated_files = false
preserve_block_start_blank_lines = false
merge_derives = true
use_try_shorthand = true
use_field_init_shorthand = false
force_explicit_abi = true
condense_wildcard_suffixes = false
required_version = "2.0.0-rc.2"
unstable_features = false
hide_parse_errors = false
error_on_line_overflow = false
error_on_unformatted = false
ignore = []
